// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type CreateEmailSubscriptionInput struct {
	Email string `json:"email"`
}

type RegisterNodeInput struct {
	Pubkey  string `json:"pubkey"`
	Address string `json:"address"`
}

type RegisterUserInput struct {
	DeviceToken string             `json:"deviceToken"`
	Node        *RegisterNodeInput `json:"node"`
}

type VerifyEmailSubscriptionInput struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}
